on: [push, pull_request]

name: debug

jobs:
  debug:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Run
        shell: Rscript {0}
        run: |
          install.packages("processx")
          processx::run(Sys.which("git"), "--version")
